from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_auto_page_break(True, margin=15)
pdf.set_font('Arial', 'B', 16)
pdf.cell(0, 10, 'Gokularamanan K', ln=1)
pdf.set_font('Arial', '', 12)
pdf.cell(0, 8, 'Biomedical Engineer | Data Analysis | Android & IoT Development', ln=1)
pdf.ln(4)
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Contact', ln=1)
pdf.set_font('Arial', '', 12)
pdf.cell(0, 8, 'Phone: +91 7448345598', ln=1)
pdf.cell(0, 8, 'Email: gokul301016@gmail.com', ln=1)
pdf.cell(0, 8, 'GitHub: github.com/GokulBIOME', ln=1)
pdf.cell(0, 8, 'LinkedIn: linkedin.com/in/gokularamanan-k-48223266', ln=1)
pdf.ln(5)
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Education', ln=1)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 8, 'Sri Manakula Vinayagar Engineering College\nB.Tech in Biomedical Engineering (2022-2026)\n\nAmalorpavam Higher Secondary School\n10th: 83% (2018-2019)\n12th: 87% (2020-2021)')
pdf.ln(3)
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Projects', ln=1)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 8, 'Abnormal Brain Connectivity with STGNN: Research on neurological disorder detection using spatial-temporal graph neural networks.\n\nLow-Cost Myoelectric Prosthetic Arm: Participated in an SHI project to build a low-cost prosthetic arm prototype with design planning and research documentation.\n\nBreast Cancer Classifier: Built an optimized breast cancer classifier using medical datasets to improve prediction accuracy.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Skills', ln=1)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 8, 'Java (Intermediate), SQL (Intermediate), MATLAB, Android Studio, Data Analysis & Visualization, ThingSpeak, Cursor AI.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Internships & Certifications', ln=1)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 8, 'Cybersecurity virtual internship (AICTE)\nZero trust cloud security virtual internship (AICTE)\nBiomedical Engineering at School Healthcare (1 Month)\nBiomedical instrumentation and human assistive devices\nAndroid Developer - Google Virtual Internship\nMATLAB Onramp by MATLAB (2025)\nEmbedded using Arduino, ML for Medical Diagnostics\nNPTEL: IoT, Classics in Neuroscience')
pdf.output('resume.pdf')
